# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-12 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_auther', models.CharField(max_length=20)),
                ('comment_text', models.CharField(max_length=500)),
                ('comment_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_auther', models.CharField(max_length=50)),
                ('post_title', models.CharField(max_length=50)),
                ('post_summary', models.CharField(max_length=500)),
                ('post_text', models.CharField(max_length=5000)),
                ('post_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='weblog_summary',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='weblog_text',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='weblog_title',
        ),
        migrations.AddField(
            model_name='weblog',
            name='weblog_auther',
            field=models.CharField(default=b'naser', max_length=250),
        ),
    ]
