# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-12 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170712_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='weblog_date',
            field=models.CharField(default=b'naser', max_length=50),
        ),
        migrations.AlterField(
            model_name='weblog',
            name='weblog_auther',
            field=models.CharField(max_length=250),
        ),
    ]
