# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-12 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170712_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='weblog_date',
            field=models.CharField(max_length=50),
        ),
    ]
