# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-13 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170712_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_auther',
        ),
        migrations.AddField(
            model_name='user',
            name='user_token',
            field=models.CharField(default=b'', max_length=40),
        ),
    ]
