# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-13 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170713_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.CharField(max_length=40),
        ),
    ]
