# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-14 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_user_default_weblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_weblog',
            field=models.CharField(max_length=10),
        ),
    ]
