# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-17 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20170714_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='posts_words',
            field=models.CharField(default=b'', max_length=100000),
        ),
    ]
