# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-18 14:04
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_weblog_posts_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='word_dic',
            field=picklefield.fields.PickledObjectField(default=[b'fancy', {}], editable=False),
        ),
    ]
