# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-19 18:11
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_weblog_word_dic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='word_dic',
            field=picklefield.fields.PickledObjectField(default={}, editable=False),
        ),
    ]
