# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-21 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20170719_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(default=b'', upload_to=b''),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default=b'', upload_to=b''),
        ),
        migrations.AddField(
            model_name='weblog',
            name='weblog_title',
            field=models.CharField(default=b'', max_length=250),
        ),
    ]
